apiVersion: 1

datasources:
  - name: CloudWatch
    type: cloudwatch
    uid: DS_CLOUDWATCH
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      authType: default
      defaultRegion: us-east-1
